version: "3"
services:
  agent:
    image: golang:1.12.1-alpine
    depends_on:
      - api
    volumes:
      - ./agent:/usr/local/src
    environment:
      - API_URL=http://api:5000
      - API_KEY=123
    working_dir: /usr/local/src
    command: go run .
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 5000
    volumes:
      - ./api:/usr/local/src
    environment:
      - PORT=5000
      - VIRTUAL_HOST=api.owl.localhost
      - DATABASE_URL=postgres://postgres:123@db/postgres?sslmode=disable
  client:
    build: ./client
    ports:
      - 3000
    volumes:
      - ./client:/usr/local/src
    environment:
      - VIRTUAL_HOST=owl.localhost
      - REACT_APP_API_URL=http://api.owl.localhost
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=123
