version: "3"
services:
    agent:
        build: ./agent
        volumes:
            - .:/src/owl
        working_dir: /src/owl/agent
    api:
        build: ./api
        volumes:
            - .:/src/owl
        working_dir: /src/owl/api
    srv:
        build: ./srv
        volumes:
            - .:/src/owl
        working_dir: /src/owl/srv
        ports:
            - 5000
        environment:
            - PORT=5000
            - API_KEY=123
            - VIRTUAL_HOST=api.owl.localhost
            - DATABASE_URL=postgres://postgres:123@db/postgres?sslmode=disable
        depends_on:
            - db
    client:
        build: ./client
        ports:
            - 3000
        volumes:
            - ./client:/src
        environment:
            - VIRTUAL_HOST=owl.localhost
            - REACT_APP_API_URL=http://api.owl.localhost
    db:
        image: postgres:11-alpine
        ports:
            - 5432
        environment:
            - POSTGRES_PASSWORD=123
            - PGPASSWORD=123
